const englishCopy = {
  languageToggle: "ខ្មែរ",
  openCart: "Open cart",
  adminLogin: "Admin login",
  cart: "Selection",
  heroEyebrow: "Tobacco-leaf free · curated in Cambodia",
  heroTitleA: "A quieter ritual",
  heroTitleB: "for your moment.",
  heroBody: "A considered collection of nicotine pouches for current adult nicotine users. No smoke, ash, or device.",
  adultOnly: "Adults 18+ only · Contains addictive nicotine",
  shopCollection: "Shop the collection",
  telegram: "Telegram order",
  collectionEyebrow: "The reserve",
  collectionTitle: "The collection",
  collectionBody: "",
  loadingProducts: "Loading live catalog from PostgreSQL…",
  catalogDatabase: "",
  catalogFallback: "Laravel API is unavailable — showing the local catalog.",
  available: "Available",
  inStock: "In stock",
  stockLeft: "left",
  sample: "Sample slot",
  notOrderable: "Not available to order",
  add: "ADD",
  added: "Added",
  addToCart: "Add to cart",
  buy: "ORDER NOW",
  orderNow: "ORDER NOW",
  details: "View details",
  productDetails: "Product details",
  tastingNotes: "Profile notes",
  releaseTime: "Release time",
  strength: "Strength",
  origin: "Origin",
  perTin: "Per tin",
  addSelection: "Add to selection",
  removeItem: "Remove item",
  decreaseQuantity: "Decrease quantity",
  increaseQuantity: "Increase quantity",
  close: "Close",
  emptyCart: "Your selection is empty.",
  subtotal: "Subtotal",
  deliveryFee: "Delivery",
  total: "Total",
  quantity: "Quantity",
  checkout: "Checkout",
  backToCart: "Back to selection",
  checkoutIntro: "Add your details, then pay the exact checkout total by QR or ABA link.",
  fullName: "Full name",
  phone: "Phone number",
  province: "Province",
  district: "District / Khan",
  deliveryNote: "Street, house number, landmark, or delivery instructions",
  payment: "Payment method",
  ageConfirmation: "I confirm that I am 18+ and currently use nicotine.",
  sendTelegram: "Send order to Telegram",
  saveOrder: "Save order & open Telegram",
  savingOrder: "Saving order…",
  creatingPayment: "Preparing payment…",
  paymentQrTitle: "Pay by QR or ABA link",
  paymentQrBody: "Pay the exact total to the merchant shown below. Only the authenticated ABA Telegram bot alert can mark the order paid.",
  payExactAmount: "Pay exact amount",
  scanToPay: "Scan to pay",
  openPaymentLink: "Open ABA payment link",
  paymentLinkInstructions: "In ABA, check the recipient and enter the exact total shown here. Opening the link does not confirm payment.",
  receiptUploadTitle: "Upload payment receipt",
  receiptUploadHelp: "Choose or take a clear receipt photo. OCR will read and submit it automatically. JPG, PNG or WebP, up to 5 MB.",
  receiptChoosePhoto: "Choose photo",
  receiptTakePhoto: "Take photo",
  receiptReplace: "Replace photo",
  receiptRemove: "Remove photo",
  receiptPreviewAlt: "Selected payment receipt",
  receiptScanning: "Reading receipt…",
  receiptScanFound: "Receipt read. Sending it for Telegram verification…",
  receiptScanNotFound: "We could not read this receipt clearly. Choose or take a clearer photo.",
  receiptScanFailed: "The receipt scan could not finish. Choose or take another photo.",
  receiptInvalid: "Use a readable JPG, PNG or WebP under 5 MB, no more than 6000 pixels per side or 16 megapixels.",
  productSummary: "Items",
  timeRemaining: "Time remaining",
  paymentSupportMessage: "After paying, upload or take a receipt photo. OCR reads and submits it automatically, then the authenticated Telegram bot verifies the payment. Do not pay again while waiting.",
  expiresAt: "Expires",
  claimingPayment: "Saving claim…",
  paymentClaimedTitle: "Waiting for Telegram verification",
  paymentClaimedBody: "Your receipt is saved. The order will be marked paid only after the authenticated Telegram bot matches the receipt with the checkout payment.",
  missingQrTitle: "Missing exact QR",
  missingQrBody: "No saved QR matches this server-calculated total. Please contact the seller before paying.",
  unavailableTotal: "Unavailable total",
  contactSeller: "Contact @b_imv",
  paymentQrUnavailable: "No saved QR matches this exact total. Please contact the seller.",
  sessionExpiredTitle: "Checkout expired",
  sessionExpiredBody: "If you have not paid, create a new checkout. If you already paid, contact the seller with your bank receipt; do not pay again.",
  sessionCancelledTitle: "Checkout cancelled",
  sessionCancelledBody: "This payment session was cancelled. Create a new checkout if you still want to order.",
  cancelPayment: "Cancel payment",
  cancellingPayment: "Cancelling…",
  cancelPaymentConfirm: "Cancel this payment session? Do this only if you have not paid.",
  retryCheckout: "Create new checkout",
  checkoutSessionStatus: "Session status",
  networkUnavailable: "Network is unstable. We will keep checking without marking this paid.",
  paidTitle: "Paid",
  paidBody: "The Telegram bot verified your payment and saved your order. Confirm delivery details with the seller on Telegram.",
  confirmOnTelegram: "CONFIRM ORDER ON TELEGRAM",
  openingTelegramIn: "Opening Telegram in",
  openTelegram: "Open Telegram",
  copyMessage: "Copy message",
  copiedMessage: "Message copied.",
  home: "Home",
  required: "Please complete all required fields.",
  orderApiError: "The order could not be saved. Check that the Laravel API is running, then try again.",
  orderReady: "Order ready",
  orderReadyBody: "Telegram has opened with your order. Send it to @b_imv and wait for price, delivery, and payment confirmation.",
  orderSavedBody: "Your order has been saved. Telegram opened with the same details so the seller can confirm it.",
  orderNumber: "Order number",
  continueShopping: "Continue shopping",
  ageTitle: "Age verification",
  ageBody: "This website sells nicotine products only to current nicotine users aged 18 or older.",
  ageCheck: "I confirm I am 18 years or older and an existing nicotine or tobacco user.",
  enter: "Enter store",
  footerWarning: "",
  independent: "",
};

export type StoreCopy = { [Key in keyof typeof englishCopy]: string };

const khmerCopy: StoreCopy = {
  languageToggle: "English",
  openCart: "បើកកន្ត្រក",
  adminLogin: "ចូល Admin",
  cart: "កន្ត្រក",
  heroEyebrow: "គ្មានស្លឹកថ្នាំជក់ · ជ្រើសរើសសម្រាប់កម្ពុជា",
  heroTitleA: "ជម្រើសស្ងប់ស្ងាត់",
  heroTitleB: "សម្រាប់ពេលវេលារបស់អ្នក។",
  heroBody: "Nicotine pouches សម្រាប់អ្នកប្រើ nicotine ពេញវ័យបច្ចុប្បន្ន។ គ្មានផ្សែង ផេះ ឬឧបករណ៍។",
  adultOnly: "សម្រាប់មនុស្សពេញវ័យ 18+ · មាន nicotine ",
  shopCollection: "មើលផលិតផល",
  telegram: "កម្ម៉ង់តាម Telegram",
  collectionEyebrow: "ផលិតផលជ្រើសរើស",
  collectionTitle: "ផលិតផលទាំងអស់",
  collectionBody: "",
  loadingProducts: "កំពុងទាញផលិតផលពី ",
  catalogDatabase: "",
  catalogFallback: "Laravel API មិនអាចភ្ជាប់បាន — កំពុងបង្ហាញ local catalog។",
  available: "មានលក់",
  inStock: "មានស្តុក",
  stockLeft: "នៅសល់",
  sample: "Sample",
  notOrderable: "មិនទាន់អាចកម្ម៉ង់បាន",
  add: "ADD",
  added: "បានដាក់",
  addToCart: "ដាក់ចូលកន្ត្រក",
  buy: "ORDER NOW",
  orderNow: "ORDER NOW",
  details: "មើលព័ត៌មាន",
  productDetails: "ព័ត៌មានផលិតផល",
  tastingNotes: "ក្លិន និងរសជាតិ",
  releaseTime: "រយៈពេល",
  strength: "កម្លាំង",
  origin: "ប្រភព",
  perTin: "ក្នុងមួយប្រអប់",
  addSelection: "ដាក់ចូលកន្ត្រក",
  removeItem: "លុបផលិតផល",
  decreaseQuantity: "បន្ថយចំនួន",
  increaseQuantity: "បន្ថែមចំនួន",
  close: "បិទ",
  emptyCart: "កន្ត្រករបស់អ្នកនៅទទេ។",
  subtotal: "សរុបផលិតផល",
  deliveryFee: "ដឹកជញ្ជូន",
  total: "សរុប",
  quantity: "ចំនួន",
  checkout: "បន្តទៅ Checkout",
  backToCart: "ត្រឡប់ទៅកន្ត្រក",
  checkoutIntro: "បំពេញព័ត៌មាន រួចបង់ចំនួនសរុបតាម QR ឬតំណ ABA។",
  fullName: "ឈ្មោះពេញ",
  phone: "លេខទូរសព្ទ",
  province: "ខេត្ត / រាជធានី",
  district: "ស្រុក / ខណ្ឌ",
  deliveryNote: "ផ្លូវ លេខផ្ទះ ទីតាំងសម្គាល់ ឬព័ត៌មានដឹកជញ្ជូន",
  payment: "វិធីទូទាត់",
  ageConfirmation: "ខ្ញុំបញ្ជាក់ថាខ្ញុំមានអាយុ 18+ និងជាអ្នកប្រើ nicotine បច្ចុប្បន្ន។",
  sendTelegram: "ផ្ញើ Order ទៅ Telegram",
  saveOrder: "រក្សាទុក Order និងបើក Telegram",
  savingOrder: "កំពុងរក្សាទុក Order…",
  creatingPayment: "កំពុងរៀបចំការទូទាត់…",
  paymentQrTitle: "បង់ប្រាក់តាម QR ឬតំណ ABA",
  paymentQrBody: "សូមបង់ចំនួនសរុបទៅអ្នកទទួលខាងក្រោម។ មានតែ ABA Telegram bot ផ្លូវការប៉ុណ្ណោះដែលអាចបញ្ជាក់ថាបានបង់។",
  payExactAmount: "ចំនួនត្រូវបង់",
  scanToPay: "ស្កេនដើម្បីបង់ប្រាក់",
  openPaymentLink: "បើកតំណទូទាត់ ABA",
  paymentLinkInstructions: "ក្នុង ABA សូមពិនិត្យអ្នកទទួល និងបញ្ចូលចំនួនសរុបខាងលើ។ ការបើកតំណមិនមានន័យថាបានបង់ប្រាក់ទេ។",
  receiptUploadTitle: "បង្ហោះរូបថតបង្កាន់ដៃទូទាត់",
  receiptUploadHelp: "ជ្រើសរើស ឬថតរូបបង្កាន់ដៃឲ្យច្បាស់។ OCR នឹងអាន និងផ្ញើដោយស្វ័យប្រវត្តិ។ JPG, PNG ឬ WebP មិនលើស 5 MB។",
  receiptChoosePhoto: "ជ្រើសរើសរូបថត",
  receiptTakePhoto: "ថតរូប",
  receiptReplace: "ប្ដូររូបថត",
  receiptRemove: "លុបរូបថត",
  receiptPreviewAlt: "រូបបង្កាន់ដៃទូទាត់ដែលបានជ្រើសរើស",
  receiptScanning: "កំពុងអានបង្កាន់ដៃ…",
  receiptScanFound: "បានអានបង្កាន់ដៃ។ កំពុងផ្ញើទៅផ្ទៀងផ្ទាត់តាម Telegram…",
  receiptScanNotFound: "មិនអាចអានបង្កាន់ដៃនេះបានច្បាស់ទេ។ សូមជ្រើសរើស ឬថតរូបថ្មីឲ្យច្បាស់ជាងនេះ។",
  receiptScanFailed: "ការស្កេនបង្កាន់ដៃមិនបានសម្រេច។ សូមជ្រើសរើស ឬថតរូបផ្សេង។",
  receiptInvalid: "សូមប្រើ JPG, PNG ឬ WebP ដែលអាចអានបាន ក្រោម 5 MB មិនលើស 6000 ភីកសែលក្នុងមួយជ្រុង ឬ 16 មេហ្គាភីកសែល។",
  productSummary: "ផលិតផល",
  timeRemaining: "ពេលនៅសល់",
  paymentSupportMessage: "បន្ទាប់ពីបង់ សូមបង្ហោះ ឬថតរូបបង្កាន់ដៃ។ OCR នឹងអាន និងផ្ញើដោយស្វ័យប្រវត្តិ បន្ទាប់មក Telegram bot ផ្លូវការនឹងផ្ទៀងផ្ទាត់ការទូទាត់។ កុំបង់ម្ដងទៀត។",
  expiresAt: "ផុតកំណត់",
  claimingPayment: "កំពុងរក្សាទុកការបញ្ជាក់…",
  paymentClaimedTitle: "កំពុងរង់ចាំ Telegram ផ្ទៀងផ្ទាត់",
  paymentClaimedBody: "បានរក្សាទុកបង្កាន់ដៃ។ Order នឹងបង្ហាញថាបានបង់ តែបន្ទាប់ពី Telegram bot ផ្លូវការផ្ទៀងផ្ទាត់បង្កាន់ដៃជាមួយការទូទាត់ Checkout។",
  missingQrTitle: "មិនមាន QR ចំនួននេះ",
  missingQrBody: "គ្មាន QR ដែលត្រូវនឹងចំនួនសរុបដែល server បានគណនា។ សូមទាក់ទងអ្នកលក់មុនបង់ប្រាក់។",
  unavailableTotal: "ចំនួនមិនទាន់មាន QR",
  contactSeller: "ទាក់ទង @b_imv",
  paymentQrUnavailable: "គ្មាន QR ដែលត្រូវនឹងចំនួនសរុបនេះទេ។ សូមទាក់ទងអ្នកលក់។",
  sessionExpiredTitle: "Checkout ផុតកំណត់",
  sessionExpiredBody: "បើមិនទាន់បង់ សូមបង្កើត Checkout ថ្មី។ បើបានបង់រួច សូមទាក់ទងអ្នកលក់ជាមួយបង្កាន់ដៃធនាគារ ហើយកុំបង់ម្ដងទៀត។",
  sessionCancelledTitle: "បានបោះបង់ Checkout",
  sessionCancelledBody: "Payment session នេះត្រូវបានបោះបង់។ សូមបង្កើត Checkout ថ្មី ប្រសិនបើអ្នកចង់កម្ម៉ង់បន្ត។",
  cancelPayment: "បោះបង់ payment",
  cancellingPayment: "កំពុងបោះបង់…",
  cancelPaymentConfirm: "តើបោះបង់ payment session នេះមែនទេ? សូមធ្វើបែបនេះតែពេលមិនទាន់បង់ប្រាក់។",
  retryCheckout: "បង្កើត Checkout ថ្មី",
  checkoutSessionStatus: "ស្ថានភាព Session",
  networkUnavailable: "Network មិនសូវនឹងនរ។ យើងនឹងបន្តពិនិត្យ ដោយមិនបង្ហាញថា Paid ទេ។",
  paidTitle: "Paid",
  paidBody: "Telegram bot បានផ្ទៀងផ្ទាត់ការទូទាត់ និងរក្សាទុកកម្ម៉ង់។ សូមបញ្ជាក់ព័ត៌មានដឹកជញ្ជូនជាមួយអ្នកលក់តាម Telegram។",
  confirmOnTelegram: "CONFIRM ORDER ON TELEGRAM",
  openingTelegramIn: "កំពុងបើក Telegram ក្នុង",
  openTelegram: "បើក Telegram",
  copyMessage: "Copy Message",
  copiedMessage: "បាន copy message។",
  home: "Home",
  required: "សូមបំពេញព័ត៌មានដែលចាំបាច់ទាំងអស់។",
  orderApiError: "មិនអាចរក្សាទុក Order បានទេ។ សូមពិនិត្យថា Laravel API កំពុងដំណើរការ រួចសាកល្បងម្តងទៀត។",
  orderReady: "Order រួចរាល់",
  orderReadyBody: "Telegram បានបើកជាមួយព័ត៌មាន order។ សូមផ្ញើទៅ @b_imv ហើយរង់ចាំបញ្ជាក់តម្លៃ ការដឹកជញ្ជូន និង payment។",
  orderSavedBody: "Order របស់អ្នកត្រូវបានរក្សាទុក។ Telegram បានបើកជាមួយព័ត៌មានដូចគ្នា ដើម្បីឲ្យអ្នកលក់បញ្ជាក់។",
  orderNumber: "លេខ Order",
  continueShopping: "បន្តទិញ ",
  ageTitle: "បញ្ជាក់អាយុ",
  ageBody: "Website នេះលក់ផលិតផល nicotine សម្រាប់អ្នកប្រើ nicotine បច្ចុប្បន្នដែលមានអាយុ 18 ឆ្នាំឡើង។",
  ageCheck: "ខ្ញុំបញ្ជាក់ថាខ្ញុំមានអាយុ 18 ឆ្នាំឡើង និងជាអ្នកប្រើ nicotine ឬ tobacco បច្ចុប្បន្ន។",
  enter: "ចូលហាង",
  footerWarning: "",
  independent: "",
};

export const STORE_COPY: Record<"en" | "km", StoreCopy> = {
  en: englishCopy,
  km: khmerCopy,
};
